### ISSUE TITLE
invalid urls for trained models

### ISSUE THREAD

**Issue by rogercmq** [IBM/action-recognition-pytorch#7]
The I3D-R50 checkpoint from https://ibm.ent.box.com/v/SSV2-I3D-ResNet-50-f32 is inception-based, which is not resnet50. Meanwhile, the I3D-R101 url is outdated: https://ibm.ent.box.com/v/SSV2-I3D-ResNet-101-f32.

**Comment by chunfuchen** [comment]
Thanks for reporting the errors, the links are fixed. Please let me know if you still encounter the issue

**Comment by rogercmq** [comment]
Thx for your reply! But I still cant get access to the SSV2 checkpoints since I dont have an IBM Box.com account.

**Comment by chunfuchen** [comment]
@rogercmq sorry for the inconvenience, I just change the permission

**Comment by UmmeHadi** [comment]
Can you please help me , how to load datasets in this repo? I am a beginner. please provide link of any stepwise instructions if possible.
